datafacts_root: datafacts

data_ingestion:
  root_dir: datafacts/data_ingestion
  source_URL: https://github.com/gssrenathkumar/Dataset/raw/main/Chicken%20Disease%20Classifier%20Dataset.zip
  local_data_file: datafacts/data_ingestion/data.zip
  unzip_dir: datafacts/data_ingestion


prepare_base_model:
  root_dir: datafacts/prepare_base_model
  base_model_path: datafacts/prepare_base_model/base_model.h5
  updated_base_model_path: datafacts/prepare_base_model/base_model_updated.h5
