datafacts_root: datafacts

data_ingestion:
  root_dir: datafacts/data_ingestion
  source_URL: https://github.com/gssrenathkumar/Dataset/raw/main/Chicken%20Disease%20Image%20Dataset.rar
  local_data_file: datafacts/data_ingestion/data.zip
  unzip_dir: datafacts/data_ingestion
